### ISSUE TITLE
Знайти готель у центрі

### ISSUE THREAD

**Issue by ulianamytnyk99** [ulianamytnyk99/Uliana99#2]
Готель "Віва"

**Comment by ulianamytnyk99** [comment]
![fr01](https://user-images.githubusercontent.com/38036558/38865739-64c3357a-4247-11e8-9cfb-c72abfff45f3.jpg)

**Comment by romaniukoksana** [comment]
дуже гарний краєвид)

**Comment by ulianamytnyk99** [comment]
але ж дуже дорого!!!
